### ISSUE TITLE
getting crash 

### ISSUE THREAD

**Issue by meetgori1** [FunkyMuse/MediaPicker#9]
FATAL EXCEPTION: main
                                                         Process: com.wellnessguru, PID: 28985
                                                         java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.
                                                         	at com.bumptech.glide.Glide.throwIncorrectGlideModule(Glide.java:370)
                                                         	at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:362)
                                                         	at com.bumptech.glide.Glide.get(Glide.java:190)
                                                         	at com.bumptech.glide.Glide.getRetriever(Glide.java:791)
                                                         	at com.bumptech.glide.Glide.with(Glide.java:902)
                                                         	at com.crazylegend.audiopicker.adapters.single.AudioSingleViewHolder.bind(AudioSingleViewHolder.kt:28)
                                                         	at com.crazylegend.audiopicker.adapters.single.AudioSingleAdapter.onBindViewHolder(AudioSingleAdapter.kt:26)
                                                         	at com.crazylegend.audiopicker.adapters.single.AudioSingleAdapter.onBindViewHolder(AudioSingleAdapter.kt:17)

for audio picker i am 
getting crash audio has a thumbnail image

**Comment by FunkyMuse** [comment]
feel free to open a PR
